#!/bin/bash
# Dockhand Migration Checklist
# Execute this interactively to track migration progress

echo "=== Dockhand Migration Checklist ==="
echo ""
echo "Before Migration:"
echo "  [ ] Backed up Portainer data (/volume2/docker/portainer)"
echo "  [ ] Backed up .env files (stacks/*/.env)"
echo "  [ ] Verified all compose.yaml files are valid"
echo "  [ ] Read MIGRATION.md completely"
echo ""
echo "Deployment:"
echo "  [ ] Created /volume2/docker/dockhand directory"
echo "  [ ] Copied dockhand-start.sh to /usr/local/etc/rc.d/dockhand.sh"
echo "  [ ] Made RC script executable (chmod +x)"
echo "  [ ] Ran RC script: sudo /usr/local/etc/rc.d/dockhand.sh"
echo "  [ ] Verified Dockhand container is running"
echo "  [ ] Confirmed health check passing (healthy)"
echo "  [ ] Accessed web UI at http://10.0.1.15:3866"
echo ""
echo "Initialization:"
echo "  [ ] Created admin user in Dockhand"
echo "  [ ] Added DS723 Docker environment (Unix socket)"
echo "  [ ] Registered container registries (GitHub, Codeberg, Quay.io)"
echo "  [ ] Cleaned default templates (optional)"
echo ""
echo "Git Webhook Setup:"
echo "  [ ] Generated webhook secret in Dockhand Settings"
echo "  [ ] Registered webhook in GitHub repo"
echo "  [ ] Tested webhook with sample commit/push"
echo ""
echo "Stack Import:"
echo "  [ ] Started importing low-risk stacks (it-tools, homepage, dozzle)"
echo "  [ ] Verified container health for each stack"
echo "  [ ] Checked label preservation (docker inspect)"
echo "  [ ] Imported databases stack (backup first)"
echo "  [ ] Imported ollama stack (allow time for model pulls)"
echo "  [ ] Imported remaining stacks"
echo ""
echo "Validation:"
echo "  [ ] All containers running and healthy"
echo "  [ ] Watchtower labels preserved (com.centurylinklabs.watchtower.enable)"
echo "  [ ] Port bindings correct (10.0.1.15 only, no 0.0.0.0)"
echo "  [ ] Security options applied (no-new-privileges, etc.)"
echo "  [ ] Volumes mounted correctly"
echo "  [ ] Git webhook auto-syncing stacks on repo push"
echo ""
echo "Cleanup:"
echo "  [ ] Stopped Portainer containers"
echo "  [ ] Removed Portainer RC script"
echo "  [ ] Deleted Portainer containers"
echo "  [ ] Archived Portainer data for rollback (optional)"
echo ""
echo "Documentation:"
echo "  [ ] Committed all changes to git"
echo "  [ ] Updated team/documentation with new access URL (http://10.0.1.15:3866)"
echo "  [ ] Documented any custom configurations in MIGRATION.md"
echo ""
echo "Post-Migration Monitoring:"
echo "  [ ] Monitored for 24 hours (stack stability)"
echo "  [ ] Tested git webhook on real commit"
echo "  [ ] Verified watchtower respects database labels"
echo "  [ ] Deleted Portainer backup (after 2-4 weeks confidence period)"
echo ""
echo "=== Checklist Complete ==="
